import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-subscription-billing-revenue-leakage-recovery",
  "engine": "recovery",
  "title": "Subscription Billing Revenue Leakage Recovery",
  "shortTitle": "Subscription Billing Revenue Leakage Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through subscription billing revenue leakage recovery",
  "industry": "Recurring Revenue Assurance",
  "uiPort": 4592,
  "apiPort": 5592,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Subscription Billing Revenue Leakage Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect product catalogs, customer contracts, entitlements, subscriptions, usage events, commitments, price books, discounts, renewals, invoices, credits, and collections in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "billedRevenue",
    "expectedKey": "supportedRevenue",
    "actualLabel": "Billed Recurring Revenue",
    "expectedLabel": "Contract-Supported Revenue",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Subscription Billing Revenue Leakage Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("product-catalog-versioning","SBR01","Product catalog versioning","Execute product catalog versioning using product catalogs, customer contracts, entitlements, subscriptions, usage events, commitments, price books, discounts, renewals, invoices, credits, and collections.","Produce a governed product catalog versioning decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Customer / Subscription Portfolio","text","Customer / Subscription Portfolio · Standard Case"],["caseReference","Product catalog versioning Reference","text","SBR01-2026-001"],["billedRevenue","Billed Recurring Revenue","currency",438500],["supportedRevenue","Contract-Supported Revenue","currency",517430],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedRevenue",subjects:["Product catalog versioning case","Customer contract ingestion case","Entitlement registry case","Subscription lifecycle control case","Usage-event ingestion case"]}),
feature("customer-contract-ingestion","SBR02","Customer contract ingestion","Execute customer contract ingestion using product catalogs, customer contracts, entitlements, subscriptions, usage events, commitments, price books, discounts, renewals, invoices, credits, and collections.","Produce a governed customer contract ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Customer / Subscription Portfolio","text","Customer / Subscription Portfolio · Standard Case"],["caseReference","Customer contract ingestion Reference","text","SBR02-2026-001"],["billedRevenue","Billed Recurring Revenue","currency",438500],["supportedRevenue","Contract-Supported Revenue","currency",517430],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedRevenue",subjects:["Product catalog versioning case","Customer contract ingestion case","Entitlement registry case","Subscription lifecycle control case","Usage-event ingestion case"]}),
feature("entitlement-registry","SBR03","Entitlement registry","Execute entitlement registry using product catalogs, customer contracts, entitlements, subscriptions, usage events, commitments, price books, discounts, renewals, invoices, credits, and collections.","Produce a governed entitlement registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Customer / Subscription Portfolio","text","Customer / Subscription Portfolio · Standard Case"],["caseReference","Entitlement registry Reference","text","SBR03-2026-001"],["billedRevenue","Billed Recurring Revenue","currency",438500],["supportedRevenue","Contract-Supported Revenue","currency",517430],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedRevenue",subjects:["Product catalog versioning case","Customer contract ingestion case","Entitlement registry case","Subscription lifecycle control case","Usage-event ingestion case"]}),
feature("subscription-lifecycle-control","SBR04","Subscription lifecycle control","Execute subscription lifecycle control using product catalogs, customer contracts, entitlements, subscriptions, usage events, commitments, price books, discounts, renewals, invoices, credits, and collections.","Produce a governed subscription lifecycle control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Customer / Subscription Portfolio","text","Customer / Subscription Portfolio · Standard Case"],["caseReference","Subscription lifecycle control Reference","text","SBR04-2026-001"],["billedRevenue","Billed Recurring Revenue","currency",438500],["supportedRevenue","Contract-Supported Revenue","currency",517430],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedRevenue",subjects:["Product catalog versioning case","Customer contract ingestion case","Entitlement registry case","Subscription lifecycle control case","Usage-event ingestion case"]}),
feature("usage-event-ingestion","SBR05","Usage-event ingestion","Execute usage-event ingestion using product catalogs, customer contracts, entitlements, subscriptions, usage events, commitments, price books, discounts, renewals, invoices, credits, and collections.","Produce a governed usage-event ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Customer / Subscription Portfolio","text","Customer / Subscription Portfolio · Standard Case"],["caseReference","Usage-event ingestion Reference","text","SBR05-2026-001"],["billedRevenue","Billed Recurring Revenue","currency",438500],["supportedRevenue","Contract-Supported Revenue","currency",517430],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedRevenue",subjects:["Product catalog versioning case","Customer contract ingestion case","Entitlement registry case","Subscription lifecycle control case","Usage-event ingestion case"]}),
feature("minimum-commitment-validation","SBR06","Minimum commitment validation","Execute minimum commitment validation using product catalogs, customer contracts, entitlements, subscriptions, usage events, commitments, price books, discounts, renewals, invoices, credits, and collections.","Produce a governed minimum commitment validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Customer / Subscription Portfolio","text","Customer / Subscription Portfolio · Standard Case"],["caseReference","Minimum commitment validation Reference","text","SBR06-2026-001"],["billedRevenue","Billed Recurring Revenue","currency",438500],["supportedRevenue","Contract-Supported Revenue","currency",517430],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedRevenue",subjects:["Product catalog versioning case","Customer contract ingestion case","Entitlement registry case","Subscription lifecycle control case","Usage-event ingestion case"]}),
feature("proration-recalculation","SBR07","Proration recalculation","Execute proration recalculation using product catalogs, customer contracts, entitlements, subscriptions, usage events, commitments, price books, discounts, renewals, invoices, credits, and collections.","Produce a governed proration recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Customer / Subscription Portfolio","text","Customer / Subscription Portfolio · Standard Case"],["caseReference","Proration recalculation Reference","text","SBR07-2026-001"],["billedRevenue","Billed Recurring Revenue","currency",438500],["supportedRevenue","Contract-Supported Revenue","currency",517430],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedRevenue",subjects:["Product catalog versioning case","Customer contract ingestion case","Entitlement registry case","Subscription lifecycle control case","Usage-event ingestion case"]}),
feature("discount-expiration-monitoring","SBR08","Discount expiration monitoring","Execute discount expiration monitoring using product catalogs, customer contracts, entitlements, subscriptions, usage events, commitments, price books, discounts, renewals, invoices, credits, and collections.","Produce a governed discount expiration monitoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Customer / Subscription Portfolio","text","Customer / Subscription Portfolio · Standard Case"],["caseReference","Discount expiration monitoring Reference","text","SBR08-2026-001"],["billedRevenue","Billed Recurring Revenue","currency",438500],["supportedRevenue","Contract-Supported Revenue","currency",517430],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedRevenue",subjects:["Product catalog versioning case","Customer contract ingestion case","Entitlement registry case","Subscription lifecycle control case","Usage-event ingestion case"]}),
feature("renewal-uplift-enforcement","SBR09","Renewal uplift enforcement","Execute renewal uplift enforcement using product catalogs, customer contracts, entitlements, subscriptions, usage events, commitments, price books, discounts, renewals, invoices, credits, and collections.","Produce a governed renewal uplift enforcement decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Customer / Subscription Portfolio","text","Customer / Subscription Portfolio · Standard Case"],["caseReference","Renewal uplift enforcement Reference","text","SBR09-2026-001"],["billedRevenue","Billed Recurring Revenue","currency",438500],["supportedRevenue","Contract-Supported Revenue","currency",517430],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedRevenue",subjects:["Product catalog versioning case","Customer contract ingestion case","Entitlement registry case","Subscription lifecycle control case","Usage-event ingestion case"]}),
feature("overage-billing-calculation","SBR10","Overage billing calculation","Execute overage billing calculation using product catalogs, customer contracts, entitlements, subscriptions, usage events, commitments, price books, discounts, renewals, invoices, credits, and collections.","Produce a governed overage billing calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Customer / Subscription Portfolio","text","Customer / Subscription Portfolio · Standard Case"],["caseReference","Overage billing calculation Reference","text","SBR10-2026-001"],["billedRevenue","Billed Recurring Revenue","currency",438500],["supportedRevenue","Contract-Supported Revenue","currency",517430],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedRevenue",subjects:["Product catalog versioning case","Customer contract ingestion case","Entitlement registry case","Subscription lifecycle control case","Usage-event ingestion case"]}),
feature("tax-and-currency-validation","SBR11","Tax and currency validation","Execute tax and currency validation using product catalogs, customer contracts, entitlements, subscriptions, usage events, commitments, price books, discounts, renewals, invoices, credits, and collections.","Produce a governed tax and currency validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Customer / Subscription Portfolio","text","Customer / Subscription Portfolio · Standard Case"],["caseReference","Tax and currency validation Reference","text","SBR11-2026-001"],["billedRevenue","Billed Recurring Revenue","currency",438500],["supportedRevenue","Contract-Supported Revenue","currency",517430],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedRevenue",subjects:["Product catalog versioning case","Customer contract ingestion case","Entitlement registry case","Subscription lifecycle control case","Usage-event ingestion case"]}),
feature("missing-invoice-detection","SBR12","Missing invoice detection","Execute missing invoice detection using product catalogs, customer contracts, entitlements, subscriptions, usage events, commitments, price books, discounts, renewals, invoices, credits, and collections.","Produce a governed missing invoice detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Customer / Subscription Portfolio","text","Customer / Subscription Portfolio · Standard Case"],["caseReference","Missing invoice detection Reference","text","SBR12-2026-001"],["billedRevenue","Billed Recurring Revenue","currency",438500],["supportedRevenue","Contract-Supported Revenue","currency",517430],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedRevenue",subjects:["Product catalog versioning case","Customer contract ingestion case","Entitlement registry case","Subscription lifecycle control case","Usage-event ingestion case"]}),
feature("credit-and-refund-audit","SBR13","Credit and refund audit","Execute credit and refund audit using product catalogs, customer contracts, entitlements, subscriptions, usage events, commitments, price books, discounts, renewals, invoices, credits, and collections.","Produce a governed credit and refund audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Customer / Subscription Portfolio","text","Customer / Subscription Portfolio · Standard Case"],["caseReference","Credit and refund audit Reference","text","SBR13-2026-001"],["billedRevenue","Billed Recurring Revenue","currency",438500],["supportedRevenue","Contract-Supported Revenue","currency",517430],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedRevenue",subjects:["Product catalog versioning case","Customer contract ingestion case","Entitlement registry case","Subscription lifecycle control case","Usage-event ingestion case"]}),
feature("corrected-billing-workflow","SBR14","Corrected billing workflow","Execute corrected billing workflow using product catalogs, customer contracts, entitlements, subscriptions, usage events, commitments, price books, discounts, renewals, invoices, credits, and collections.","Produce a governed corrected billing workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Customer / Subscription Portfolio","text","Customer / Subscription Portfolio · Standard Case"],["caseReference","Corrected billing workflow Reference","text","SBR14-2026-001"],["billedRevenue","Billed Recurring Revenue","currency",438500],["supportedRevenue","Contract-Supported Revenue","currency",517430],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedRevenue",subjects:["Product catalog versioning case","Customer contract ingestion case","Entitlement registry case","Subscription lifecycle control case","Usage-event ingestion case"]}),
feature("mrr-arr-and-leakage-analytics","SBR15","MRR ARR and leakage analytics","Execute mrr arr and leakage analytics using product catalogs, customer contracts, entitlements, subscriptions, usage events, commitments, price books, discounts, renewals, invoices, credits, and collections.","Produce a governed mrr arr and leakage analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Customer / Subscription Portfolio","text","Customer / Subscription Portfolio · Standard Case"],["caseReference","MRR ARR and leakage analytics Reference","text","SBR15-2026-001"],["billedRevenue","Billed Recurring Revenue","currency",438500],["supportedRevenue","Contract-Supported Revenue","currency",517430],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedRevenue",subjects:["Product catalog versioning case","Customer contract ingestion case","Entitlement registry case","Subscription lifecycle control case","Usage-event ingestion case"]})
]);
